### ISSUE TITLE
Java doc

### ISSUE THREAD

**Issue by JustAGod1** [MJaroslav/MJUtils#1]
Чувствую, что интересный мод, но не более. Не плохо было бы добавить примеров в readme и Java doc в код. Конечно не горит, но до тех пор мне сложно будет использовать эту либу.

**Comment by MJaroslav** [comment]
Комментарии к коду пишу, про javadoc думал уже, но может просто -src архив из релизов подключать? (Буду добавлять при следующих, если решу делать так).

Примеры будут, как только поборю лень и сделаю версию, которой буду доволен (чтобы не пришлось обновлять на следующий день). На curse странице мода есть несколько примеров.

**Comment by JustAGod1** [comment]
Ну src это конечно здорово. Но в самом коде разбираться тоже та еще задача. Мне например было бы интересно узнать о MultiBlockUtils поподробнее, желательно с примерами. Вообщем можно обойтись и без Java Doc(лучше конечно по ходу дела их писать. Хотя бы немного), но примеров добавить точно стоит на каждый Utils класс.

**Comment by MJaroslav** [comment]
Мультблокам я сделал только заготовку, работать над ними буду потом.

Зачем разбираться в коде, если будешь знать его результат из комментария? ;)

Ну да ладно, посмотрю javadoc'и.

**Comment by MJaroslav** [comment]
Релиз, документация (хоть и примитивная) приложена. Присутствует архив с javadoc и -src.jar архив.
Если тебя устраивает, закрываем тему.

**Comment by JustAGod1** [comment]
Все ок
